### PR TITLE
fix: Missing export fields cause module resolution errors when used as Parse Server dependency

### LINKED ISSUE #2875: server get crashed after updating to version 8.0.1
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
problem after parse package update to 8.0.1. working fine with version 8.0.0

### Steps to reproduce
Update package to 8.0.1 from 8.0.0

### Actual Outcome
server get crashed and get error `Error: Cannot find module `

### Expected Outcome
server must run properly

###  Environment
parse: 8.0.1

Server
- Parse Server version: `8.6.2`
- Operating system: `Windows`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: ``
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- Parse JS SDK version: `8.0.1`

### Logs
```
node:internal/modules/cjs/loader:1419
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module 'C:\new\number_widget\apps\OpenSignServer\node_modules\parse\lib\node\promiseUtils'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1419:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1408:15)
    at resolveExports (node:internal/modules/cjs/loader:650:14)
    at Function._findPath (node:internal/modules/cjs/loader:717:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1369:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\new\\number_widget\\apps\\OpenSignServer\\node_modules\\parse'
}

Node.js v22.21.1
[nodemon] app crashed - waiting for file changes before starting...
```

### PR DESCRIPTION
**Pull request by hajjarjoseph**
## Pull Request                                                               
                                                                                
  - Report security issues [confidentially](https://github.com/parse-community/P
  arse-SDK-JS/security/policy).                                                 
  - Any contribution is under this                                              
  [license](https://github.com/parse-community/Parse-SDK-JS/blob/alpha/LICENSE).
  - Link this pull request to an                                                
  [issue](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue). 
                                                                                
  ## Issue                                                                      
                                                                                
  Closes: #2875                                                                 
                                                                                
  ## Approach                                                                   
                                                                                
  In v8.0.1, the `exports` field was added to fix TypeScript type resolution.   
  The wildcard pattern `"./lib/*": "./lib/*"` was intended to maintain backward 
  compatibility, but Node.js v22+ doesn't consistently apply automatic `.js`    
  extension resolution through exports patterns.                                
                                                                                
  This PR adds explicit exports for the internal paths that parse-server        
  imports:                                                                      
                                                                                                                                          
  ```
"./lib/node/promiseUtils": "./lib/node/promiseUtils.js",                      
  "./lib/node/RESTController": "./lib/node/RESTController.js"       
```            
                                                                             
  These explicit entries take precedence over the wildcard and include the .js  extension, ensuring correct resolution across all Node.js versions.

<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **Chores**
  * Added new public entry points so consumers can import the promise utilities and the REST controller directly from the package, enabling simpler, explicit import paths and improved interoperability.
  * Updated public export declarations to reflect these additions and ensure the new entry points are available.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

### CODE REVIEW

**Comment by parseplatformorg** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/acinader/pr-checks/e63da23f-1d07-43f7-b669-5f1955671bd0?refs=b98243e1b3336b6dfec385f1601eaf09a251da46&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

**Comment by mtrezza** [comment]
@coderabbitai is there any other approach?

**Comment by mtrezza** [comment]
@coderabbitai what's the benefit of approach #6 over the PR's approach?

**Comment by mtrezza** [comment]
@coderabbitai yes, identify all current internal imports that parse-server uses to ensure this PR covers everything. Include the parse-server-push-adapter.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [8.0.2-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/8.0.2-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [8.0.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/8.0.2)
