### ISSUE TITLE
server get crashed after updating to version 8.0.1

### ISSUE THREAD

**Issue by prafull-opensignlabs** [parse-community/Parse-SDK-JS#2875]
### New Issue Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/Parse-SDK-JS/issues?q=is%3Aissue).
- [ ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse JS SDK](https://github.com/parse-community/Parse-SDK-JS/releases). 

### Issue Description
problem after parse package update to 8.0.1. working fine with version 8.0.0

### Steps to reproduce
Update package to 8.0.1 from 8.0.0

### Actual Outcome
server get crashed and get error `Error: Cannot find module `

### Expected Outcome
server must run properly

###  Environment
parse: 8.0.1

Server
- Parse Server version: `8.6.2`
- Operating system: `Windows`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: ``
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

Client
- Parse JS SDK version: `8.0.1`

### Logs
```
node:internal/modules/cjs/loader:1419
  const err = new Error(`Cannot find module '${request}'`);
              ^

Error: Cannot find module 'C:\new\number_widget\apps\OpenSignServer\node_modules\parse\lib\node\promiseUtils'
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:1419:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:1408:15)
    at resolveExports (node:internal/modules/cjs/loader:650:14)
    at Function._findPath (node:internal/modules/cjs/loader:717:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1369:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1025:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1030:22)
    at Function._load (node:internal/modules/cjs/loader:1192:37)
    at TracingChannel.traceSync (node:diagnostics_channel:328:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:237:24) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\new\\number_widget\\apps\\OpenSignServer\\node_modules\\parse'
}

Node.js v22.21.1
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by rjcodedev** [comment]
I am also getting same issue

**Comment by mtrezza** [comment]
The CI passes; are you able to start up a plain Parse Server? Parse 8.0.1 restricted exports, so maybe you are referencing some Parse internals in your custom code?

**Comment by hajjarjoseph** [comment]
## Root Cause                                                                 
                                                                                
  In v8.0.1, I added an `exports` field to `package.json` to fix TypeScript type
   resolution (#2849). This included a wildcard pattern `"./lib/*": "./lib/*"`  
  for backward compatibility.                                                   
                                                                                
  **The problem:** When an `exports` field is present, Node.js uses it          
  exclusively for module resolution. The wildcard resolves                      
  `require('parse/lib/node/promiseUtils')` to `./lib/node/promiseUtils` (without
   `.js` extension)                                                       
                                                                                
  **Why v8.0.0 worked:** No `exports` field meant traditional resolution, which 
  automatically tries `.js` extensions.                                         
                                                                                
  ## The Fix                                                                    
                                                                                
  I made a new pull request to fix this. Adding explicit exports with extensions for the paths parse-server uses:                                             
                                                                              
                                                                        
  ```
{                                                                             
    "./lib/node/promiseUtils": "./lib/node/promiseUtils.js",                    
    "./lib/node/RESTController": "./lib/node/RESTController.js"                 
  }   
```

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [8.0.2-alpha.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/8.0.2-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [8.0.2](https://github.com/parse-community/Parse-SDK-JS/releases/tag/8.0.2)
