### ISSUE TITLE
The package at "node_modules/parse/lib/react-native/ParseFile.js" attempted to import the Node standard library module "https"

### ISSUE THREAD

**Issue by alioguzhan** [parse-community/Parse-SDK-JS#775]
### Issue Description
With changes come with #765 causes this issue. There was a similiar issue caused by `http` package. Please see #768 . It supposed to be fixed but now i have this.

There is no problem with version `2.2.1`.

### Steps to reproduce

Try to use `parse/react-native` with version >= 2.3

### Actual Outcome

> The package at "node_modules/parse/lib/react-native/ParseFile.js" attempted to import the Node standard library module "https". It failed because React Native does not include the Node standard library.

### Environment Setup

- **Server**
  - parse-server version: `2.8.4`
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): `Back4App`

- **JS SDK**
  - JS SDK version: `2.3.1`
  - Application? (Browser, Node, React-Native, etc): `React Native`

**Comment by alejonext** [comment]
In web say `Error: Cannot find module 'http'` is the same error!

**Comment by mattvv** [comment]
It looks like this is caused by https://github.com/parse-community/Parse-SDK-JS/pull/749/files

Downgrading to 2.2.1 for now solves this for me.

**Comment by dplewis** [comment]
Can you submit a Pull Request to resolve this issue? I believe this was fixed via https://github.com/parse-community/Parse-SDK-JS/pull/765 but not tested on react-native

**Comment by natalio** [comment]
on react native "Unable to resolve module ..../node_modules/parse/lib/react-native/ParseFile.js"

**Comment by alioguzhan** [comment]
> Can you submit a Pull Request to resolve this issue? I believe this was fixed via #765 but not tested on react-native

I don't know the full scope of this `file uri upload` feature but the first thing that I can say is to not using any standard node library in `react-native/ParseFile.js` file which means reverting this feature for `react-native`. What do you think about this @dplewis 

Or i will try to find a way to implement same feature without using any standard node library.
