### ISSUE TITLE
Cloning Query object is not working with SDK 1.9.2

### ISSUE THREAD

**Issue by cartoonle** [parse-community/Parse-SDK-JS#431]
If I clone Query with "var clonedQueryObject = jQuery.extend(true, {}, queryObject);", I get "TypeError: clonedQueryObject.skip is not a function", when I'm trying to use cloned query.

It works fine with SDK 1.5.0
